### ISSUE TITLE
ImportError: cannot import name 'Literal' from 'typing'

### ISSUE THREAD

**Issue by dev-rinchin** [sb-ai-lab/Py-Boost#9]
py-boost: v0.4.1
python: 3.7
OS: Red Hat enterprise linux 8.5

https://github.com/python/typing/issues/707

**Comment by YM-225** [comment]
from py_boost.utils.tl_wrapper import TLPredictor, TLCompiledPredictor

**Comment by btbpanda** [comment]
@YM-225 As I found yesturday, this error is cauesd by `treelite` package after it was updated to `3.2.0` version. I am going to fix the requirements very soon but here is the manual fix during installation:

```
pip install -U py-boost
pip install -U treelite==3.1.0
```

**Comment by btbpanda** [comment]
Solved. Please update to 0.4.2:

`
pip install -U py-boost
`
